version: '3'
services:
  sw:
    image: nginx:alpine
    container_name: sw
    volumes:
      - ./serviceWorker:/usr/share/nginx/html
    ports:
      - "1234:80"
  http-cache:
    image: node:12
    container_name: http-cache
    working_dir: /app
    volumes:
      - ./http:/app
    ports:
      - "1244:80"