version: '3'
services:
  sw:
    image: nginx:alpine
    container_name: sw
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "1234:80"
  http-cache:
    image: node:12
    container_name: http-cache
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "1235:80"